import { BRANDS, VEHICLES } from "./data.js";//Takes brands and vehicles from data to use them

const app = document.getElementById("app");

/*
 * ROUTER PATHING
 * #/            -> Home
 * #/brands      -> Brand list
 * #/brand/:slug -> Single brand page using brandname as slug
 * #/compare     -> Compare page/ information page/ other pages
 */

function route() {
  return (location.hash || "#/").slice(1); //Gets rid of '#' from url hash, allows for easier routing/ cleaner path
}

function urlBuilder(str) {
  return str.toLowerCase().trim().replace(/\s+/g, "-");//Changes text to more url style. e.g. ' ' = '-' and uppercase becomes lower. E.g. A car like Toyota Yaris url would be toyota-yaris.
}

function linkToBrand(brandName) {//calls urlBuilder to build the url for browser search bar
  return `#/brand/${urlBuilder(brandName)}`;//e.g. brandname is called and converted to lowercase/dashes for brand/{brandname}
}

//Pages
//writes the html of each "page" into the container 'app'.

/*-------------------------------------------------------HOME PAGE-------------------------------------------------------------------------------*/

function renderHome() {//changes innerHTML to the appropriate text, multiple class ids for easier design and function
  app.innerHTML = `
    <section class="homePage">

      <div class="card compare card-overlay" onclick="location.hash='#/compare'">
        <h2>COMPARE</h2>
      </div>


      <div class="card info card-overlay" onclick="location.hash='#/information'">
        <h2>INFORMATION</h2>
      </div>

      <div class="card brands card-overlay" onclick="location.hash='#/brands'">
        <h2>BRANDS</h2>
      </div>

    </section>
  `;
}

/*-------------------------------------------------------INFORMATION PAGE-------------------------------------------------------------------------------*/

//accordion button layout for less clutter
//contains all dpecs mentioned might add more
function renderInfo() {
  app.innerHTML = `
    <h2>Car Parts & Specifications</h2>
    <p>This section explains common car parts and performance terms.</p>

    <div class="accordion-container">
      <div class="accordion">
        <div class="info-header">
          <h2>Engine & Performance</h2>
          <button>+</button>
        </div>
        <div class="info-body">
          <p><strong>Engine</strong> - The engine is what powers the cars. They convert fuel or electricity into mechanical energy to move vehicles. Its performance is influenced by a range of other factors such as cooling, engine size,and other adjacent systems.</p>
          <p><strong>Engine layout(Inline, V, Flat)</strong> - Engine layout refers to how the cylinders in an engine are arranged, layouts may vary between cars due to different needs for performance, balance, size, cost, etc.<br>
          <strong>Inline:</strong> an inline engines have their cylinders all arranged in a straight line. This is commonly used in cars as it is simple, easier to maintain, and efficient. <br>
          <strong>V:</strong> a V engines have their cylinders arranged in a V-shape. This layout can allow an engine to be more compact and is therefore used in higher-performance cars. <br>
          <strong>Flat/Boxer:</strong> a flat or boxer engine allows a car's centre of gravity to be reduce causing an increase in stability, this is acheived by laying the cylinders opposite each other horizontally.</p>
          <p><strong>Horsepower(hp)</strong> - horsepower refers to how much power an engine can produce, thus higher horsepower means a car can reach a higher speed or perform better at those speeds. </p>
          <p><strong>Torque(Nm)</strong> - torque is the rotational force which is generated by the engine. Higher torque means stronger pull and faster acceleration</strong></p>
        </div>
      </div>
      <div class="accordion">
        <div class="info-header">
          <h2>Speed & Metrics</h2>
          <button>+</button>
        </div>
        <div class="info-body">
          <p><strong>0-60</strong> - measures the time taken for a car to get to 60 miles per hour. Lower time = faster acceleration.</p>
          <p><strong>Top Speed</strong> - is the maximum speed a car can reach.</p>
          <p><strong>Weight</strong> - weight refers to how light or heavy a car is. Genrally, cars built for speed and agility, e.g. racing are aimed to be lighter, while heavier cars may provide more stability and internal systems. e.g. Sound dampening, radios and sound systems, etc.</p>
        </div>
      </div>
      <div class="accordion">
        <div class="info-header">
          <h2>Drivetrain</h2>
          <button>+</button>
        </div>
        <div class="info-body">
          <p><strong>AWD(All-Wheel-Drive)</strong> - Power is directed to all wheels. This improves grip and control, notably in conditions which may decrease traction. e.g. Snow and rain.</p>
          <p><strong>RWD(Rear-Wheel-Drive)</strong> - Power is directed to the rear wheels. Genrally used in performance cars as it helps to increase handling, acceleration, and promotes better weight distribution by seperating steering(front) and propulsion(rear).</p>
          <p><strong>FWD(Front-Wheel-Drive)</strong> - Power is directed to front wheels. Typically the most common drivetrain and is fount in most everyday vehicles as it provides stability and efficiency.</p>
        </div>
      </div>
      <div class="accordion">
        <div class="info-header">
          <h2>Engine Types</h2>
          <button>+</button>
        </div>
        <div class="info-body">
          <p><strong>Turbocharged</strong> - A turbocharger is used within engines to force more air into them. This allows for drastically improved air intake which in turn can increase an engines power and efficency.</p>
          <p><strong>Naturally Aspirated(NA)</strong> - This is how most common every-day driver engines are configured, generally to intake air naturally to power the engine.</p>
          <p><strong>Electric</strong> -  Electric "engines" are cars which use batteries to deliver isntant power. They also do not require fuel in contrast to petrol and disel cars.</p>
        </div>
      </div>
      <div class="accordion">
        <div class="info-header">
          <h2>Body Style</h2>
          <button>+</button>
        </div>
        <div class="info-body">
          <p><strong>Coupe</strong> - Coupe cars are generally promote a sportier design often with two-door and less room in the back and boot, this is due to a larger focus on performance.</p>
          <p><strong>Sedan</strong> - A sedan style car are typically 4-door with a seperate boot, typically they are more comforatble and practical for the average driver.</p>
          <p><strong>Hatchback</strong> - Hatchback cars are similar to sedans normally smaller and often sporting three or five doors(including boot), however the boot opens upwards allowing for more flexible storage space.</p>
        </div>
      </div>
    </div>
  `;

  /*Calls all accordion classes, when press change to active which allows body to change to block (visible), "=" becomes a "-".*/
  const accordions = document.querySelectorAll('.accordion');
  accordions.forEach(accordion => {
    accordion.addEventListener('click', e =>{
      let accordionBtn = accordion.querySelector('button');
      accordion.classList.toggle('active');
      if (accordionBtn.textContent === '+'){
        accordionBtn.textContent = '-';
      }
      else{
        accordionBtn.textContent = '+';
      }
    })
  })
}

/*-------------------------------------------------------BRANDS PAGE-------------------------------------------------------------------------------*/

function renderBrands() {//Writes heading and message below. 
  app.innerHTML = `
    <h2>Brands</h2>
    <p>Pick a brand to view models.</p>

  <div class="brandContainer">

    <div class="brandBtn toyotaBtn" onclick="location.hash='#/brand/toyota'">
      <h2 class="brandLabel">Toyota</h2>
     <h4 class="brandDesc">A global leader in reliability, offering practical and efficient vehicles for everyday use.</h4>
    </div>

    <div class="brandBtn subaruBtn" onclick="location.hash='#/brand/subaru'">
      <h2 class="brandLabel">Subaru</h2>
      <h4 class="brandDesc">A Japanese brand known for all-wheel drive systems and a strong rally racing heritage.</h4>
    </div>

    <div class="brandBtn mazdaBtn" onclick="location.hash='#/brand/mazda'">
      <h2 class="brandLabel">Mazda</h2>
      <h4 class="brandDesc">Focused on driving experience, Mazda combines design with innovative engineering.</h4>
    </div>

    <div class="brandBtn ferrariBtn" onclick="location.hash='#/brand/ferrari'">
      <h2 class="brandLabel">Ferrari</h2>
      <h4 class="brandDesc">An iconic Italian brand known for building high-performance sports cars with a rich racing heritage.</h4>
    </div>

    <div class="brandBtn bmwBtn" onclick="location.hash='#/brand/bmw'">
      <h2 class="brandLabel">BMW</h2>
      <h4 class="brandDesc">A premium brand combining luxury with sporty performance and advanced technology.</h4>
    </div>

    <div class="brandBtn porscheBtn" onclick="location.hash='#/brand/porsche'">
      <h2 class="brandLabel">Porsche</h2>
      <h4 class="brandDesc">Renowned for precision engineering and performance, especially its legendary sports cars.</h4>
    </div>

    <div class="brandBtn nissanBtn" onclick="location.hash='#/brand/nissan'">
      <h2 class="brandLabel">Nissan</h2>
      <h4 class="brandDesc">A versatile brand offering everything from reliable daily drivers to performance models.</h4>
    </div>

    <div class="brandBtn hondaBtn" onclick="location.hash='#/brand/honda'">
      <h2 class="brandLabel">Honda</h2>
      <h4 class="brandDesc">Known for reliability and efficiency, Honda produces a wide range of practical and sporty vehicles.</h4>
    </div>
  </div>

  `;
}/*Loops BRAND array, for each brand in BRANDS a link is added to the list.
also creates a link for each item in BRANDS. e.g. http://127.0.0.1:5500/index.html#/brands/toyota (this is the <slug>)*/

/*-------------------------------------------------------BRAND MODELS PAGE-------------------------------------------------------------------------------*/

function renderBrandPage(brandSlug) {//finds the current brand and changes to that brand page
  const brandName = BRANDS.find(b => urlBuilder(b) === brandSlug);

  if (!brandName) {
    app.innerHTML = `
      <h2>Brand not found</h2>
      <p class="backLabel"><a href="#/brands">Back to brands</a></p>
    `;
    return;
  }

   /*slug which is found in the url(name of brand)
  compares the slug (url) 
  with the brand names 
  if the brand name in the slug(url) matches the name of a brand that brands page is displayed 
  else, displays an error screen*/
  const brandVehicles = VEHICLES.filter(v => v.brand === brandName);
 
  //backticks are template literals allow for usage of variables inisde of HTML, e.g. ${brandName} e.g. Toyota, images, stats, etc. More efficient
  //.map v loops thorugh the VEHICLES data and finds each v.x and replaces that value with the data found
  app.innerHTML = `
    <h2>${brandName}</h2>

    <h3>Models:</h3>

    <div class="carcardContainer">
    ${brandVehicles.map(v =>`<div class="carCard" onclick="location.hash='#/vehicle/${v.id}'"><img src="${v.image1}" alt="${v.model}" class="carImg"><h3>${v.model}</h3></div>`).join("")}
    </div>


    <button class="backBtn" onclick="location.hash='#/brands'">Back to brands</button>
  `;
}

/*-------------------------------------------------------VEHICLE PAGE-------------------------------------------------------------------------------*/

//renders page
function renderVehiclePage(vehicleId){
    const vehicle = VEHICLES.find(v => v.id === vehicleId);//some error handling incase the car searched for doesnt exist

    if (!vehicle) {
      app.innerHTML = `
        <h2>Vehicle not found</h2>
        <button class="backBtn" onclick="location.hash='#/brands'">Back to brnads</button>
    `;
    return;
    }
    //renders page dynamically
    //button to change images for some interactivity on pages
    //calling vehicle specs + images from 'vehicle.etc' 
    //creates url using url builder
    //allows user to go back to models page
    //Button handles the current vehicle ID
    app.innerHTML = `
    <h2>${vehicle.brand} ${vehicle.model}</h2>

    <p>${vehicle.description}</p>

    <div>
      <img src="${vehicle.image1}" 
      alt="${vehicle.brand} ${vehicle.model}" 
      class="vehicle-image">
    </div>
    
    <h2>Specifications</h2>
    <h3>Engine & Performance</h3>

    <div class="textPos">
        <img src="${vehicle.image2}" alt="${vehicle.brand} ${vehicle.model} Engine" class="vehicle-image2">

        <div class="spec-text">
          <p><strong>Year:</strong> ${vehicle.year}</p>
          <p><strong>Body style:</strong> ${vehicle.bodystyle}</p>
          <p><strong>Engine type:</strong> ${vehicle.enginetype}</p>
          <p><strong>Power:</strong> ${vehicle.power}</p>
          <p><strong>Torque:</strong> ${vehicle.torque}</p>
          <p><strong>Weight:</strong> ${vehicle.weight}</p>
          <p><strong>0-60:</strong> ${vehicle.zerotosixty}</p>
          <p><strong>Top speed:</strong> ${vehicle.topspeed}</p>
          <p><strong>Drive type:</strong> ${vehicle.drivetype}</p>
          <p><strong>Price:</strong> ${vehicle.price}</p>
      
        </div>
    </div>

    <button class="backBtn" onclick="location.hash='#/brand/${urlBuilder(vehicle.brand)}'">Back to ${vehicle.brand}</button>

    <button class="compareBtn" data-id="${vehicle.id}">Add to Compare</button>

    <button class="clearBtn" onclick="clearCompareList()">Clear Compare List</button>
    `;

    //ensure that button stays in same state even after refreshing or swithcing pages
    const btn = document.querySelector(".compareBtn");
    const comparisonList = JSON.parse(localStorage.getItem("comparisonList")) || [];

  if (btn){
    const isSelected = comparisonList.includes(vehicle.id);

    //change text shown
    if (isSelected) {
      btn.textContent = "Remove from Compare";
    } else {
      btn.textContent = "Add to Compare";
    }

    //Disables button when limit of 2 is capped
    if (comparisonList.length >= 2 && !isSelected){
      btn.disabled = true;
      btn.textContent = "Compare limit reached";
    }

    btn.addEventListener("click", function(){
      toggleCompare(this.dataset.id, this);
    });
  }
}


//----------------LOGIC FOR BUTTON TO COMPARE + OTHERS-------------------------
function toggleCompare(vehicleId, button){
  let comparisonList = JSON.parse(localStorage.getItem("comparisonList")) || [];

  const isSelected = comparisonList.includes(vehicleId);

  if (isSelected){
    //Remove from list
    comparisonList = comparisonList.filter(id => id !== vehicleId);
  }
  else{
    //Only allows for 2 cars at most in the list
    if (comparisonList.length >= 2){
      return;
    }

    //Adding to list
    comparisonList.push(vehicleId);
  }

  localStorage.setItem("comparisonList", JSON.stringify(comparisonList));

  router();//reloading page
}

window.clearCompareList = function(){//window. makes function global to use for in-lin onclick calls
  localStorage.removeItem("comparisonList");//clears comparison list
  router();//reloads page
}

/*-------------------------------------------------------COMPARE PAGE-------------------------------------------------------------------------------*/

//COMPARE PAGE
//finds and reads list, if list is not 2 items long , displays the text to tell users to add more vehicles before the page can be used
function renderComparePage() {

  const comparisonList = JSON.parse(localStorage.getItem("comparisonList")) || []

  if (comparisonList.length < 2){
    app.innerHTML = `
      <h2>Compare</h2>
      <p>Select 2 vehicles to compare</p>
      <button class="backBtn" onclick="location.hash='#/brands'">Go select vehicles</button>
    `;
    return;
  }

  //Reads vehicle ids from local storage, con erts them to the vehicle ids from class VEHICLES
  const selectedVehicles = comparisonList.map(id =>
    VEHICLES.find(v => v.id === id)
  );

  //Takes information and renders the stats name and main pciture side by side.
  //.map loops through all the vehicles in the list before conerting ^, allows for scalibility/ efficiency
  //.join at bottom (combines the <div>s which would normally be seperate into one e.g. 
  // <div>Toyota</div>
  // <div>M3</div> 
  //into <div>Toyota</div><div>M3</div>
  //Compare card gets made with each vehicle occupying one, using css to show side by side
  app.innerHTML = `
    <h2>Compare Vehicles</h2>

    <div class="compareContainer">
      ${selectedVehicles.map(vehicle => `
        <div class="compareCard">
          <h3>${vehicle.brand} ${vehicle.model}</h3>

          <img src="${vehicle.image1}" 
               alt="${vehicle.brand} ${vehicle.model}" 
               class="compareImage">

          <div class="compareStats">
            <p><strong>Year:</strong> ${vehicle.year}</p>
            <p><strong>Engine:</strong> ${vehicle.enginetype}</p>
            <p><strong>Power:</strong> ${vehicle.power}</p>
            <p><strong>Torque:</strong> ${vehicle.torque}</p>
            <p><strong>0-60:</strong> ${vehicle.zerotosixty}</p>
            <p><strong>Top speed:</strong> ${vehicle.topspeed}</p>
            <p><strong>Drive:</strong> ${vehicle.drivetype}</p>
            <p><strong>Weight:</strong> ${vehicle.weight}</p>
            <p><strong>Body style:</strong> ${vehicle.bodystyle}</p>
            <p><strong>Cost:</strong> ${vehicle.price}</p>
          </div>
        </div>
      `).join("")}
    </div>

    <button class="backBtn" onclick="location.hash='#/brands'">Back to brands</button>
    <button class="clearBtn" onclick="clearCompareList()">Clear Compare List</button>
    <button class="downloadBtn" onclick="downloadCompareList()">Download Compare List</button>
  `;
}

//function to allow for downlaoading the compare list for requirement 
window.downloadCompareList = function(){
  //pulls data from local storage and puts into an array
  const comparisonList = JSON.parse(localStorage.getItem("comparisonList")) || [];//if no vehicles, use and empty array
  //loops through the all vehicles in VEHICLES, if thier id is in the comparison list it keeps them in selected vehicles
  const selectedVehicles = VEHICLES.filter(v =>comparisonList.includes(v.id));

  //converts the JS to json string, null and 2 for spacing 
  const json = JSON.stringify(selectedVehicles, null, 2);

  //creates the file
  const download = new Blob([json], {type: "application/json"});//[json] is file content and type is json
  const url = URL.createObjectURL(download);//creates a temp url turning file to temp link

  const a = document.createElement("a");//sets a download link with <a> element
  a.href = url;//the <a> element links to the temp url for the file
  a.download = "comparison-list.json";//downloads the file 
  a.click();//when they click the link ^^^
}

function renderNotFound() {//error handling  
  app.innerHTML = `
    <h2>Error 404</h2>
    <p>Page not found.</p>
    <button class="backBtn" onclick="location.hash='#/brands'">Go to home</button>
  `;
}

//Router for SPA functionaility
function router() {
  const path = route();//gets the url hash, removes hash, then decides which page to render"/brand/toyota" 
  const parts = path.split("/").filter(Boolean);

  //
  if (parts.length === 0) return renderHome();

  //"/brands"
  if (parts[0] === "brands") return renderBrands();

  //"/brand/:slug(brand)"
  if (parts[0] === "brand" && parts[1]) return renderBrandPage(parts[1]);

  //"/compare"
  if (parts[0] === "compare") return renderComparePage();

  //"/information"
  if (parts[0] === "information") return renderInfo();

  //"/vehicle/:id"
  if (parts[0] === "vehicle" && parts[1]) return renderVehiclePage(parts[1]);

  return renderNotFound();
}

window.addEventListener("hashchange", router);
router();